---
- name: Install docker and its dependencies
  ansible.builtin.import_playbook: install_docker.yml
  tags: [setup]

- name: Main playbook
  hosts: all

  tasks:

    - name: Copy config
      ansible.builtin.template:
        src: templates/.env.j2
        dest: /.env
        mode: 0644
      tags: [db_credentials, deploy]

    - name: Start redmine docker image
      community.docker.docker_container:
        name: redmine-example-app
        image: redmine:5.0.2
        env_file: /.env
        restart_policy: always
        exposed_ports: 3000
        ports:
          - 3000:3000
      tags: [redmine, deploy]

- hosts: webservers
  tasks:
    - name: Install datadog
      ansible.builtin.import_role:
        name: datadog.datadog
      tags: [monitoring, datadog]
